version: '3.8'

services:
  host-angular:
    image: generic.abp/host-angular:latest
    container_name: host-angular
    build:
      context: ../../../
      dockerfile: angular/Dockerfile.local
    ports:
      - "4200:80"
    depends_on:
      - host-api
    volumes:
      - ./dynamic-env.json://usr/share/nginx/html/dynamic-env.json
    networks:
      - abp-network

  host-api:
    image: generic.abp/host-api:latest
    container_name: host-api
    hostname: host-api
    build:
      context: ../../
      dockerfile: src/Generic.Abp.Host.HttpApi.Host/Dockerfile.local
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80;
      - Kestrel__Certificates__Default__Path=/root/certificate/localhost.pfx
      - Kestrel__Certificates__Default__Password=4fdfc5b4-1f77-4e3c-bc4e-77351a8462a1
      - App__SelfUrl=https://localhost:44354
      - App__AngularUrl=http://localhost:4200
      - App_CorsOrigins=http://localhost:4200
      - App__HealthCheckUrl=http://host-api/health-status
      - AuthServer__RequireHttpsMetadata=false
      - AuthServer__Authority=https://localhost:44354
      - App__RedirectAllowedUrls=http://localhost:4200
      - ConnectionStrings__Default=Server=mysql;Port=3306;Userid=root;Password=myPassw0rd;Database=Host;
      - Redis__Configuration=redis
    ports:
      - "44354:443"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy  
    restart: on-failure    
    volumes:
      - ./certs:/root/certificate
    networks:
      - abp-network
  

  db-migrator:
    image: generic.abp/host-db-migrator:latest
    container_name: db-migrator
    build:
      context: ../../
      dockerfile: src/Host.DbMigrator/Dockerfile.local
    environment:
      - OpenIddict__Applications__Host_App__RootUrl=http://localhost:4200
      - OpenIddict__Applications__Host_Swagger__RootUrl=https://localhost:44354
      - ConnectionStrings__Default=Server=mysql;Port=3306;Userid=root;Password=myPassw0rd;Database=Host;
      - Redis__Configuration=redis
    restart: on-failure
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - abp-network    
  
  mysql:
    container_name: mysql-db
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: myPassw0rd
    volumes:
      - mysql_data:/var/lib/mysql
    networks: 
      - abp-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 10s
      timeout: 5s
      retries: 5    
  
  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - abp-network  
    healthcheck:
      test: ["CMD", "redis-cli","ping"]      

volumes:
  mysql_data:
    name: host_mysql_data
networks:
  abp-network:
    name: host-network
    driver: bridge
