name: Push packages

on:
  push:
    branches:
      - dev
    paths:
      - 'src/common.props'

  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # 获取完整的历史记录以进行diff

      - name: Set Git Config
        run: |
          git config --global user.email "tianxiaode@htomail.com"
          git config --global user.name "tianxiaode"
      
      - name: fetch branch
        run: git fetch origin

      - name: Check for Version Change
        id: check_version
        run: .\check_version.ps1 
        working-directory: nupkg
        shell: powershell

      - name: Merge to main and release if version changed
        if: ${{ env.change }} == 'true'
        run: |
          git checkout main
          git pull origin main
          git merge dev        

      - name: Setup Dotnet
        if: ${{ env.change }} == 'true'
        uses: actions/setup-dotnet@master
        with:
          dotnet-version: '8.x'

      - name: Build All
        if: ${{ env.change }} == 'true'
        run: .\build-all-release.ps1 
        working-directory: build
        shell: powershell

      - name: Pack All
        if: ${{ env.change }} == 'true'
        run: .\pack.ps1
        working-directory: nupkg
        shell: powershell

      - name: Push All
        if: ${{ env.change }} == 'true'
        run: .\push_packages.ps1 ${{ secrets.NugetKey }}
        working-directory: nupkg
        shell: powershell
