name: Push packages

on:
  push:
    branches:
      - master
    paths:
      - 'src/**/*.cs'
      - 'src/**/*.cshtml'
      - 'src/**/*.csproj'
      - 'src/**/*.razor'

  pull_request:
    paths:
      - 'src/**/*.cs'
      - 'src/**/*.cshtml'
      - 'src/**/*.csproj'
      - 'src/**/*.razor'
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    if: ${{ !github.event.pull_request.draft }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@master
      with:
        dotnet-version: 7.0.100

    - name: Build All
      run: .\build-all-release.ps1 
      working-directory: .\build
      shell: powershell

    - name: Pack All
      run: .\pack.ps1
      working-directory: .\nupkg
      shell: powershell

    - name: Push All
      run: .\push_packages.ps1 ${{ secrets.NugetKey }}
      working-directory: .\nupkg
      shell: powershell


  
